FROM node:22-slim

WORKDIR /app


ENV PORT=8080

RUN corepack enable && corepack prepare pnpm@9.0.0 --activate

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json .npmrc ./
COPY apps ./apps
COPY packages ./packages

RUN pnpm install --frozen-lockfile

RUN pnpm --filter @repo/api... build

ENV NODE_ENV=production

EXPOSE 8080

CMD ["pnpm", "--filter", "@repo/api", "start"]