import { MemberStatus } from "../../src/generated/prisma/enums.js";

export const SEED_PLANS = [
  {
    name: "ライトプラン",
    price: 6800,
  },
  {
    name: "スタンダードプラン",
    price: 9800,
  },
  {
    name: "プレミアムプラン",
    price: 14800,
  },
];

export const SEED_MEMBERS = [
  {
    name: "佐藤 雄大",
    email: "sato.yudai@example.com",
    phone: "090-1111-0001",
    gender: "men",
    status: MemberStatus.active,
    planName: "プレミアムプラン",
  },
  {
    name: "田中 美咲",
    email: "tanaka.misaki@example.com",
    phone: "090-1111-0002",
    gender: "women",
    status: MemberStatus.active,
    planName: "スタンダードプラン",
  },
  {
    name: "中村 健二",
    email: "nakamura.kenji@example.com",
    phone: "090-1111-0003",
    gender: "men",
    status: MemberStatus.inactive,
    planName: "ライトプラン",
  },
  {
    name: "小林 竜也",
    email: "kobayashi.tatsuya@example.com",
    phone: "090-1111-0004",
    gender: "men",
    status: MemberStatus.active,
    planName: "プレミアムプラン",
  },
  {
    name: "村田 恵美",
    email: "murata.emi@example.com",
    phone: "090-1111-0005",
    gender: "women",
    status: MemberStatus.suspended,
    planName: "スタンダードプラン",
  },
  {
    name: "山田 太郎",
    email: "yamada.taro@example.com",
    phone: "090-1111-0006",
    gender: "men",
    status: MemberStatus.active,
    planName: "スタンダードプラン",
  },
  {
    name: "鈴木 杏奈",
    email: "suzuki.anna@example.com",
    phone: "090-1111-0007",
    gender: "women",
    status: MemberStatus.active,
    planName: "プレミアムプラン",
  },
  {
    name: "高橋 翔",
    email: "takahashi.sho@example.com",
    phone: "090-1111-0008",
    gender: "men",
    status: MemberStatus.active,
    planName: "ライトプラン",
  },
  {
    name: "伊藤 菜月",
    email: "ito.natsuki@example.com",
    phone: "090-1111-0009",
    gender: "women",
    status: MemberStatus.inactive,
    planName: "スタンダードプラン",
  },
  {
    name: "渡辺 優太",
    email: "watanabe.yuta@example.com",
    phone: "090-1111-0010",
    gender: "men",
    status: MemberStatus.active,
    planName: "プレミアムプラン",
  },
  {
    name: "加藤 莉子",
    email: "kato.riko@example.com",
    phone: "090-1111-0011",
    gender: "women",
    status: MemberStatus.active,
    planName: "ライトプラン",
  },
  {
    name: "吉田 直樹",
    email: "yoshida.naoki@example.com",
    phone: "090-1111-0012",
    gender: "men",
    status: MemberStatus.active,
    planName: "スタンダードプラン",
  },
  {
    name: "山本 彩",
    email: "yamamoto.aya@example.com",
    phone: "090-1111-0013",
    gender: "women",
    status: MemberStatus.suspended,
    planName: "プレミアムプラン",
  },
  {
    name: "松本 大輔",
    email: "matsumoto.daisuke@example.com",
    phone: "090-1111-0014",
    gender: "men",
    status: MemberStatus.active,
    planName: "ライトプラン",
  },
  {
    name: "井上 真央",
    email: "inoue.mao@example.com",
    phone: "090-1111-0015",
    gender: "women",
    status: MemberStatus.active,
    planName: "スタンダードプラン",
  },
  {
    name: "清水 健太",
    email: "shimizu.kenta@example.com",
    phone: "090-1111-0016",
    gender: "men",
    status: MemberStatus.inactive,
    planName: "プレミアムプラン",
  },
  {
    name: "林 さくら",
    email: "hayashi.sakura@example.com",
    phone: "090-1111-0017",
    gender: "women",
    status: MemberStatus.active,
    planName: "ライトプラン",
  },
  {
    name: "斎藤 拓海",
    email: "saito.takumi@example.com",
    phone: "090-1111-0018",
    gender: "men",
    status: MemberStatus.active,
    planName: "スタンダードプラン",
  },
  {
    name: "森田 愛",
    email: "morita.ai@example.com",
    phone: "090-1111-0019",
    gender: "women",
    status: MemberStatus.active,
    planName: "プレミアムプラン",
  },
  {
    name: "石川 陸",
    email: "ishikawa.riku@example.com",
    phone: "090-1111-0020",
    gender: "men",
    status: MemberStatus.suspended,
    planName: "ライトプラン",
  },
];
